// Maps exercise names from the shared library (supabase `exercises.name`) to a
// matching illustration in the vendored open-source asset set under
// public/exercise-illustrations/<slug>/frame-{1,2,3}.svg.
//
// Source: derived from Everkinetic (CC BY-SA 4.0) via bryllim/workout-guide
// (https://github.com/bryllim/workout-guide, CC BY-SA 4.0 for the artwork).
// Attribution lives on the mentions-légales page.
//
// Deliberately hand-curated, not fuzzy-matched: physio-app's library is a
// clinical rehab exercise set (397 entries, mostly condition-specific
// variants), while the asset set is a general gym/calisthenics catalog (302
// entries). Only entries below are confident the illustrated movement matches
// what the exercise name actually describes — a wrong illustration would show
// a patient the wrong movement. Exercises with no entry here fall back to the
// existing hand-drawn ExerciseIllustration pictogram, same as before.
export const EXERCISE_ILLUSTRATION_MAP: Record<string, string> = {
  // Cat-cow

  // Glute bridge family
  "Pont fessier (coxarthrose)": "glute-bridge",
  "Weighted Single-Leg Glute Bridge": "single-leg-glute-bridge",
  "Heel-Driven Glute Bridge (Hamstring Focus)": "glute-bridge",

  // Squat family
  "Mini Wall Sit (Shallow)": "wall-sit",
  "Isometric Wall Sit (60 Degrees)": "wall-sit",
  // NOTE: "Renforcement progressif du quadriceps, chaise" was removed from here —
  // despite the name, its instructions describe a seated knee-extension exercise
  // ("Assis, tendez lentement la jambe jusqu'à l'horizontale..."), not a wall-sit.
  // Falls back to the placeholder until a correct match is found.
  "Controlled Mini-Squat (Knee Arthritis)": "bodyweight-squat",
  "Limited-Range Squat (Hip)": "bodyweight-squat",
  "Squat fonctionnel complet (hanche)": "bodyweight-squat",
  "Assisted Partial Squat": "bodyweight-squat",
  "Protected Squat (Quadriceps)": "bodyweight-squat",
  "ACL-Protected Squat (Limited Range)": "bodyweight-squat",
  "Light Closed-Chain Quad Strengthening": "bodyweight-squat",

  // Lunges
  "Lateral Lunge (Band)": "lateral-lunge",

  // Core / plank
  "Gentle Supine Core Bracing (Hernia)": "plank",
  "Modified Plank (Knees)": "plank",
  "Postural Core Bracing": "plank",
  "Anti-Rotation Hold (Band)": "pallof-press",
  "Modified Side Plank (Light)": "side-plank",
  "Dynamic Plank (Limb Movement)": "plank",

  // Quadruped / hip extension
  "Quadruped Scapular Stability": "bird-dog",

  // Clamshell / hip abduction
  "Clamshell (Band)": "clamshell",
  "Progressive Clamshell": "clamshell",
  "Side-Lying Hip Abduction (Band)": "side-lying-hip-abduction",
  "Renforcement léger des abducteurs, allongé": "side-lying-hip-abduction",

  // Lateral band walk

  // Stretches
  "Étirement des pectoraux à la porte": "doorway-chest-stretch",
  "Wall Calf Stretch (Bent Knee, Soleus)": "wall-calf-stretch",
  "Étirement des ischio-jambiers (genou arthrose)": "hamstring-stretch",
  "Gentle Supine Hamstring Stretch": "hamstring-stretch",
  "Étirement des ischio-jambiers assis (sciatique)": "seated-forward-fold-stretch",
  "Shoulder Circles": "arm-circles",
  "Lying Torso Rotation": "torso-twist-stretch",
  "Rotation lombaire allongée": "torso-twist-stretch",

  // Gait / cardio
  "Assisted Progressive Walking": "walking",
  "Assisted Progressive Walking (Post-Knee-Replacement)": "walking",
  "Progressive Walk-to-Jog (Shin Splints, Soft Terrain)": "walking",
  "Fractionated Short Walks": "walking",
  "Forward-Leaning Walk (Short Duration)": "walking",
  "Unassisted Prolonged Walking (Hip)": "walking",
  "Progressive Brisk Walking": "walking",
  "Walking on Varied Terrain": "walking",
  "Seated Stationary Cycling (Forward Lean)": "cycling",
  "Stationary Cycling (No Resistance)": "cycling",
  "Stationary Cycling (Low Resistance, Meniscus)": "cycling",
  "Marching in Place (Warm-Up)": "walking",
  "Controlled Lateral Jump (Hip/Knee Alignment)": "skater-hop",

  // Steps
  "Controlled Stair Climbing": "step-up",
  "Assisted Low Step-Up (Slow)": "step-up",
  "Montée de marche contrôlée (genou arthrose)": "step-up",

  // Calf raises
  "Slow Bilateral Calf Raise": "calf-raise",
  "Assisted Calf Raise (Post-Achilles)": "calf-raise",
  "Assisted Standing Calf Raise": "calf-raise",
  "Eccentric Calf Raise (Bent Knee, Soleus)": "calf-raise",
  "Eccentric Calf Raise (Straight Knee, Single-Leg)": "calf-raise",
  "Isometric Calf Hold (Resistance)": "calf-raise",
  "Isometric Calf Hold": "calf-raise",

  // Wrist
  "Wrist Extension (Light Dumbbell)": "wrist-extension",
  "Eccentric Wrist Extension": "wrist-extension",
  "Isometric Wrist Extension": "wrist-extension",
  "Wrist Extension (Band)": "wrist-extension",
  "Wrist Curl (Light Dumbbell)": "wrist-curl",
  "Eccentric Wrist Curl": "wrist-curl",

  // Wall push-up
  "Wall Finger Walk (Shoulder Mobility)": "wall-push-up",

  // Misc single matches
  "Bicep Curl (Water Bottle)": "bicep-curl",
  "Front Raise (Bodyweight)": "front-raise",
  "Limited Front Raise (Pain-Guided)": "front-raise",
  "Assisted Front Raise": "front-raise",
  "Single-Leg Romanian Deadlift (Light, Bodyweight)": "romanian-deadlift",

  // ---------------------------------------------------------------------------
  // Everkinetic base import — all 302 Everkinetic exercises, added as their
  // own standalone library entries (English name kept as-is; see
  // supabase/migrations/0034). Since these ARE Everkinetic exercises, name
  // and illustration slug correspond directly — no fuzzy matching involved.
  // Some of these slugs are also reused above by a hand-matched French
  // clinical name (e.g. "calf-raise") — that's expected duplication, not
  // a bug; see the migration file's header comment.
  // ---------------------------------------------------------------------------
  "Bench Press": "bench-press",
  "Incline Bench Press": "incline-bench-press",
  "Incline Dumbbell Press": "incline-dumbbell-press",
  "Dumbbell Bench Press": "dumbbell-bench-press",
  "Decline Bench Press": "decline-bench-press",
  "Machine Chest Press": "machine-chest-press",
  "Pec Deck": "pec-deck",
  "Cable Fly": "cable-fly",
  "Push-up": "push-up",
  "Weighted Push-up": "weighted-push-up",
  "Overhead Press": "overhead-press",
  "Dumbbell Seated Shoulder Press": "seated-dumbbell-press",
  "Arnold Press": "arnold-press",
  "Lateral Raise": "lateral-raise",
  "Cable Lateral Raise": "cable-lateral-raise",
  "Front Raise": "front-raise",
  "Rear Delt Fly": "rear-delt-fly",
  "Reverse Pec Deck": "reverse-pec-deck",
  "Face Pull": "face-pull",
  "Upright Row": "upright-row",
  "Deadlift": "deadlift",
  "Romanian Deadlift": "romanian-deadlift",
  "Barbell Row": "barbell-row",
  "T-Bar Row": "t-bar-row",
  "Dumbbell Bent Over Row": "dumbbell-bent-over-row",
  "One-Arm Dumbbell Row": "one-arm-dumbbell-row",
  "Chest Supported Row": "chest-supported-row",
  "Seated Cable Row": "seated-row",
  "Machine Row": "machine-row",
  "Lat Pulldown": "lat-pulldown",
  "Close-Grip Lat Pulldown": "close-grip-lat-pulldown",
  "Straight-Arm Pulldown": "straight-arm-pulldown",
  "Pull-up": "pull-up",
  "Assisted Pull-up": "assisted-pull-up",
  "Weighted Pull-up": "weighted-pull-up",
  "Chin-up": "chin-up",
  "Barbell Shrug": "shrug",
  // The clinical library's French "Squat" (bodyweight) was merged into
  // "Bodyweight Squat" as a duplicate (see migration 0042) — this barbell
  // "Squat" is now the only exercise left with this exact name.
  "Squat": "squat",
  "Front Squat": "front-squat",
  "Hack Squat": "hack-squat",
  "Leg Press": "leg-press",
  "Bulgarian Split Squat": "bulgarian-split-squat",
  "Walking Lunge": "walking-lunge",
  "Step-Up": "step-up",
  "Leg Extension": "leg-extension",
  "Leg Curl": "leg-curl",
  "Seated Leg Curl": "seated-leg-curl",
  "Hip Thrust": "hip-thrust",
  "Glute Bridge": "glute-bridge",
  "Good Morning": "good-morning",
  "Standing Calf Raise": "standing-calf-raise",
  "Seated Calf Raise": "seated-calf-raise",
  "Bicep Curl": "bicep-curl",
  "Hammer Curl": "hammer-curl",
  "Preacher Curl": "preacher-curl",
  "Cable Curl": "cable-curl",
  "Reverse Curl": "reverse-curl",
  "Wrist Curl": "wrist-curl",
  "Tricep Pushdown": "tricep-pushdown",
  "Overhead Tricep Extension": "overhead-tricep-extension",
  "Skull Crusher": "skull-crusher",
  "Close-Grip Bench Press": "close-grip-bench-press",
  "Dip": "dip",
  "Assisted Dip": "assisted-dip",
  "Plank": "plank",
  "Side Plank": "side-plank",
  "Hanging Leg Raise": "hanging-leg-raise",
  "Cable Crunch": "cable-crunch",
  "Ab Wheel Rollout": "ab-wheel",
  "Running": "running",
  "Walking": "walking",
  "Cycling": "cycling",
  "Rowing": "rowing",
  "Stair Climber": "stair-climber",
  "Dumbbell Fly": "dumbbell-fly",
  "Incline Cable Fly": "incline-cable-fly",
  "Decline Dumbbell Press": "decline-dumbbell-press",
  "Smith Machine Bench Press": "smith-machine-bench-press",
  "Landmine Press": "landmine-press",
  "Chest Dip": "chest-dip",
  "Weighted Dip": "weighted-dip",
  "Machine Shoulder Press": "machine-shoulder-press",
  "Standing Dumbbell Press": "standing-dumbbell-press",
  "Push Press": "push-press",
  "Machine Lateral Raise": "machine-lateral-raise",
  "Cable Front Raise": "cable-front-raise",
  "Plate Front Raise": "plate-front-raise",
  "Bent-Over Rear Delt Raise": "bent-over-rear-delt-raise",
  "Cable Rear Delt Fly": "cable-rear-delt-fly",
  "Pendlay Row": "pendlay-row",
  "Inverted Row": "inverted-row",
  "Meadows Row": "meadows-row",
  "Single-Arm Cable Row": "single-arm-cable-row",
  "Wide-Grip Lat Pulldown": "wide-grip-lat-pulldown",
  "Neutral-Grip Pull-up": "neutral-grip-pull-up",
  "Assisted Chin-up": "assisted-chin-up",
  "Weighted Chin-up": "weighted-chin-up",
  "Rack Pull": "rack-pull",
  "Back Extension": "back-extension",
  "Dumbbell Shrug": "dumbbell-shrug",
  "Goblet Squat": "goblet-squat",
  "Smith Machine Squat": "smith-machine-squat",
  "Belt Squat": "belt-squat",
  "Sumo Deadlift": "sumo-deadlift",
  "Trap Bar Deadlift": "trap-bar-deadlift",
  "Lying Leg Curl": "lying-leg-curl",
  "Nordic Hamstring Curl": "nordic-hamstring-curl",
  "Single-Leg Romanian Deadlift": "single-leg-romanian-deadlift",
  "Reverse Lunge": "reverse-lunge",
  "Split Squat": "split-squat",
  "Cable Kickback": "cable-kickback",
  "Hip Abduction Machine": "hip-abduction-machine",
  "Single-Leg Glute Bridge": "single-leg-glute-bridge",
  "Barbell Glute Bridge": "barbell-glute-bridge",
  "Dumbbell Glute Bridge": "dumbbell-glute-bridge",
  "Dumbbell Hip Thrust": "dumbbell-hip-thrust",
  "Smith Machine Hip Thrust": "smith-machine-hip-thrust",
  "Smith Machine Romanian Deadlift": "smith-machine-romanian-deadlift",
  "Dumbbell Romanian Deadlift": "dumbbell-romanian-deadlift",
  "Kettlebell Romanian Deadlift": "kettlebell-romanian-deadlift",
  "Cable Pull-Through": "cable-pull-through",
  "Machine Glute Kickback": "machine-glute-kickback",
  "Cable Standing Hip Abduction": "cable-standing-hip-abduction",
  "Cable Standing Hip Adduction": "cable-standing-hip-adduction",
  "Hip Adduction Machine": "hip-adduction-machine",
  "Smith Machine Bulgarian Split Squat": "smith-machine-bulgarian-split-squat",
  "Smith Machine Reverse Lunge": "smith-machine-reverse-lunge",
  "Smith Machine Split Squat": "smith-machine-split-squat",
  "Heel-Elevated Goblet Squat": "heel-elevated-goblet-squat",
  "Dumbbell Sumo Squat": "dumbbell-sumo-squat",
  "Dumbbell Sumo Deadlift": "dumbbell-sumo-deadlift",
  "Front-Foot Elevated Split Squat": "front-foot-elevated-split-squat",
  "Deficit Reverse Lunge": "deficit-reverse-lunge",
  "Dumbbell Lateral Lunge": "dumbbell-lateral-lunge",
  "Dumbbell Curtsy Lunge": "dumbbell-curtsy-lunge",
  "Landmine Squat": "landmine-squat",
  "Landmine Romanian Deadlift": "landmine-romanian-deadlift",
  "Kettlebell Swing": "kettlebell-swing",
  "Glute-Focused Back Extension": "glute-focused-back-extension",
  "Reverse Hyperextension": "reverse-hyperextension",
  "Donkey Calf Raise": "donkey-calf-raise",
  "Leg Press Calf Raise": "leg-press-calf-raise",
  "Wall Sit": "wall-sit",
  "Jump Squat": "jump-squat",
  "Incline Dumbbell Curl": "incline-dumbbell-curl",
  "Concentration Curl": "concentration-curl",
  "EZ-Bar Curl": "ez-bar-curl",
  "Spider Curl": "spider-curl",
  "Rope Hammer Curl": "rope-hammer-curl",
  "Drag Curl": "drag-curl",
  "Rope Tricep Pushdown": "rope-tricep-pushdown",
  "Two Dumbbell Skullcrusher": "dumbbell-skull-crusher",
  "Single Dumbbell Skullcrusher": "single-dumbbell-skullcrusher",
  "Dumbbell Overhead Tricep Extension": "dumbbell-overhead-tricep-extension",
  "Single Arm Dumbbell Tricep Extension": "single-arm-dumbbell-tricep-extension",
  "Bench Dip": "bench-dip",
  "Tricep Kickback": "tricep-kickback",
  "Wrist Extension": "wrist-extension",
  "Farmer Carry": "farmer-carry",
  "Crunch": "crunch",
  "Reverse Crunch": "reverse-crunch",
  "Russian Twist": "russian-twist",
  "Bicycle Crunch": "bicycle-crunch",
  "Mountain Climber": "mountain-climber",
  "Dead Bug": "dead-bug",
  "Bird Dog": "bird-dog",
  "Pallof Press": "pallof-press",
  "Cable Woodchop": "cable-woodchop",
  "Half-Kneeling Pallof Press": "half-kneeling-pallof-press",
  "Cable Pallof Hold": "cable-pallof-hold",
  "Hanging Knee Raise": "hanging-knee-raise",
  "Captain's Chair Knee Raise": "captains-chair-knee-raise",
  "Decline Sit-Up": "decline-sit-up",
  "Weighted Crunch": "weighted-crunch",
  "Weighted Russian Twist": "weighted-russian-twist",
  "Dumbbell Side Bend": "dumbbell-side-bend",
  "Elliptical": "elliptical",
  "Swimming": "swimming",
  "Jump Rope": "jump-rope",
  "Assault Bike": "assault-bike",
  "SkiErg": "skierg",
  "Hiking": "hiking",
  "Treadmill Incline Walk": "treadmill-incline-walk",
  "Battle Ropes": "battle-ropes",
  "Incline Push-up": "incline-push-up",
  "Knee Push-up": "knee-push-up",
  "Wide Push-up": "wide-push-up",
  "Diamond Push-up": "diamond-push-up",
  "Decline Push-up": "decline-push-up",
  "Pike Push-up": "pike-push-up",
  "Feet-Elevated Pike Push-up": "feet-elevated-pike-push-up",
  "Archer Push-up": "archer-push-up",
  "Typewriter Push-up": "typewriter-push-up",
  "Explosive Push-up": "explosive-push-up",
  "Hindu Push-up": "hindu-push-up",
  "Scapular Push-up": "scapular-push-up",
  "Push-up Shoulder Tap": "push-up-shoulder-tap",
  "Wall Push-up": "wall-push-up",
  "Wall Walk": "wall-walk",
  "Wall Handstand Push-up": "wall-handstand-push-up",
  "Handstand Push-up": "handstand-push-up",
  "Chair Dip": "chair-dip",
  "Doorway Row": "doorway-row",
  "Towel Row": "towel-row",
  "Prone Y Raise": "prone-y-raise",
  "Prone T Raise": "prone-t-raise",
  "Superman": "superman",
  "Superman Hold": "superman-hold",
  "Reverse Snow Angel": "reverse-snow-angel",
  "Dead Hang": "dead-hang",
  "Active Hang": "active-hang",
  "Scapular Pull-up": "scapular-pull-up",
  "Negative Pull-up": "negative-pull-up",
  "Commando Pull-up": "commando-pull-up",
  "L-Sit Pull-up": "l-sit-pull-up",
  "Towel Pull-up": "towel-pull-up",
  "Bodyweight Squat": "bodyweight-squat",
  "Pistol Squat": "pistol-squat",
  "Assisted Pistol Squat": "assisted-pistol-squat",
  "Shrimp Squat": "shrimp-squat",
  "Cossack Squat": "cossack-squat",
  "Sissy Squat": "sissy-squat",
  "Forward Lunge": "forward-lunge",
  "Lateral Lunge": "lateral-lunge",
  "Curtsy Lunge": "curtsy-lunge",
  "Skater Squat": "skater-squat",
  "Single-Leg Box Squat": "single-leg-box-squat",
  "Step-Down": "step-down",
  "Calf Raise": "calf-raise",
  "Single-Leg Calf Raise": "single-leg-calf-raise",
  "Glute Bridge March": "glute-bridge-march",
  "Frog Pump": "frog-pump",
  "Donkey Kick": "donkey-kick",
  "Fire Hydrant": "fire-hydrant",
  "Clamshell": "clamshell",
  "Hip Airplane": "hip-airplane",
  "Side-Lying Hip Abduction": "side-lying-hip-abduction",
  "Side-Lying Leg Raise": "side-lying-leg-raise",
  "Lying Hamstring Walkout": "lying-hamstring-walkout",
  "Towel Hamstring Curl": "towel-hamstring-curl",
  "Stability Ball Hamstring Curl": "stability-ball-hamstring-curl",
  "Banded Glute Bridge": "banded-glute-bridge",
  "Banded Hip Thrust": "banded-hip-thrust",
  "Banded Frog Pump": "banded-frog-pump",
  "Banded Clamshell": "banded-clamshell",
  "Banded Lateral Walk": "banded-lateral-walk",
  "Banded Monster Walk": "banded-monster-walk",
  "Banded Squat": "banded-squat",
  "Banded Donkey Kick": "banded-donkey-kick",
  "Banded Fire Hydrant": "banded-fire-hydrant",
  "Banded Kickback": "banded-kickback",
  "Banded Standing Hip Abduction": "banded-standing-hip-abduction",
  "Banded Seated Hip Abduction": "banded-seated-hip-abduction",
  "Band Pull-Apart": "band-pull-apart",
  "Banded Face Pull": "banded-face-pull",
  "Banded Row": "banded-row",
  "Banded Lat Pulldown": "banded-lat-pulldown",
  "Banded Pallof Press": "banded-pallof-press",
  "Banded Woodchop": "banded-woodchop",
  "Banded Dead Bug": "banded-dead-bug",
  "Hollow Body Hold": "hollow-body-hold",
  "Hollow Rock": "hollow-rock",
  "V-Up": "v-up",
  "Flutter Kick": "flutter-kick",
  "Lying Leg Raise": "lying-leg-raise",
  "Toe Touch": "toe-touch",
  "Heel Tap": "heel-tap",
  "Plank Shoulder Tap": "plank-shoulder-tap",
  "Plank Jack": "plank-jack",
  "Bear Plank": "bear-plank",
  "Bear Crawl": "bear-crawl",
  "Crab Walk": "crab-walk",
  "Inchworm": "inchworm",
  "L-Sit Hold": "l-sit-hold",
  "Seated Knee Tuck": "seated-knee-tuck",
  "Side Plank Hip Dip": "side-plank-hip-dip",
  "Copenhagen Plank": "copenhagen-plank",
  "Dragon Flag": "dragon-flag",
  "Burpee": "burpee",
  "Half Burpee": "half-burpee",
  "Squat Thrust": "squat-thrust",
  "High Knees": "high-knees",
  "Jumping Jack": "jumping-jack",
  "Skater Hop": "skater-hop",
  "Lateral Shuffle": "lateral-shuffle",
  "Fast Feet": "fast-feet",
  "Sprawl": "sprawl",
  "Seal Jack": "seal-jack",
  "Cat-Cow Stretch": "cat-cow-stretch",
  "Arm Circles": "arm-circles",
  "World's Greatest Stretch": "worlds-greatest-stretch",
  "Leg Swings": "leg-swings-stretch",
  "Torso Twists": "torso-twist-stretch",
  "Doorway Chest Stretch": "doorway-chest-stretch",
  "Child's Pose": "childs-pose",
  "Kneeling Hip Flexor Stretch": "kneeling-hip-flexor-stretch",
  "Hamstring Stretch": "hamstring-stretch",
  "Standing Quad Stretch": "standing-quad-stretch",
  "Seated Forward Fold": "seated-forward-fold-stretch",
  "Cross-Body Shoulder Stretch": "cross-body-shoulder-stretch",
  "Wall Calf Stretch": "wall-calf-stretch",
  "Butterfly Stretch": "butterfly-stretch",
};
